name: tests
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-22.04
    env:
      QT_QPA_PLATFORM: minimal        # run Qt without a real X server
      QT_PREFERRED_BINDING: PySide6
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      # Qt 6 fails without these system libraries
      - name: Install Qt runtime libraries
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            libegl1-mesa libgl1-mesa-dev \
            libxcb-cursor0 libxcb-icccm4 libxcb-image0 \
            libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 \
            libxcb-xfixes0 libxcb-xinerama0 libxkbcommon-x11-0 \
            libportaudio2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          pip install -r dev-requirements.txt

      - name: Run tests
        run: pytest -ra -q
